server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exercise_project
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
token:
  jwtKey: "weixy"
  validity: 86400000
file:
  path: D:\public
  url: http://127.0.0.1:8081/
